version: "3.8"
services:
  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=activityhub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  pub-sub-emulator:
    image: google/cloud-sdk:latest
    command:
      [
        "gcloud",
        "beta",
        "emulators",
        "pubsub",
        "start",
        "--host-port=0.0.0.0:8085",
        "--project=local-env",
      ]
    ports:
      - "8085:8085"
  api:
    build:
      context: "./backend"
      dockerfile: "./Dockerfile"
    image: "activityhub_api"
    env_file: ./backend/.env
    environment:
      - DB_HOST=postgresql
    depends_on:
      - postgresql
      - pub-sub-emulator
    ports:
      - "8080:8080"
  app:
    build:
      context: "./app"
      dockerfile: "./Dockerfile"
    image: "activityhub_app"
    ports:
      - "5173:80"

volumes:
  db:
    driver: local
