name: Go test
on:
  pull_request:
    paths:
      - "backend/**"
  push:
    branches:
      - master
    paths:
      - "backend/**"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Build
        run: |
          cd backend
          go build -v ./...

      - name: Test
        run: |
          cd backend
          go test -v ./...
